title: nvim-config
description: My personal neovim config.
first_commit: { iso: "2024-02-02T09:38:24-08:00", timeZone: "America/Los_Angeles" }
links:
    - { type: git, url: "https://github.com/RemasteredArch/nvim-config" }
